<template>
  <section class="activity-page">
    <header><div><h2>{{ t('Activity') }}</h2><p>{{ t('Local usage and runtime health.') }}</p></div><div class="activity-actions"><button type="button" :disabled="loading" @click="load">{{ loading ? t('Loading…') : t('Refresh') }}</button><button v-if="runtime" type="button" @click="copySummary">{{ copied ? t('Copied') : t('Copy summary') }}</button></div></header>
    <div v-if="data" class="activity-summary"><div v-for="item in summaryItems" :key="item.label" class="activity-metric"><span>{{ item.label }}</span><strong>{{ item.value }}</strong></div></div>
    <div v-if="runtime" class="runtime-panel"><div class="runtime-heading"><div><h3>{{ t('Runtime diagnostics') }}</h3><p>{{ runtime.appServer.command || t('App-server') }} · {{ runtime.appServer.lifecycle }}</p></div><span class="runtime-state" :data-state="runtime.appServer.lifecycle">{{ runtime.appServer.lifecycle }}</span></div><div class="runtime-counters"><span>{{ t('Pending RPC') }} <b>{{ runtime.appServer.pendingRpcCount }}</b></span><span>{{ t('Active turns') }} <b>{{ runtime.appServer.activeTurnCount }}</b></span><span>{{ t('Server requests') }} <b>{{ runtime.appServer.pendingServerRequestCount }}</b></span><span>{{ t('WebSocket clients') }} <b>{{ runtime.websocket.activeSubscribers }}</b></span></div><p v-if="runtime.appServer.lastError" class="runtime-error">{{ runtime.appServer.lastError.message }}</p><p v-else-if="runtime.appServer.lastExit" class="runtime-note">{{ t('Last exit') }}: {{ runtime.appServer.lastExit.code ?? 'signal' }}</p><div class="runtime-events"><div v-for="event in runtime.recentEvents.slice(0, 12)" :key="event.atIso + event.kind" class="runtime-event"><time>{{ formatTime(event.atIso) }}</time><span>{{ event.kind }}</span></div></div></div>
    <div v-if="error" class="activity-error"><strong>{{ t('Activity is unavailable') }}</strong><p>{{ error }}</p></div><div v-else-if="!data" class="activity-loading">{{ t('Loading activity…') }}</div>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getCodexActivitySummary, getRuntimeDiagnostics, type CodexActivitySummary, type RuntimeDiagnosticsSnapshot } from '../../api/codexGateway'
import { useUiLanguage } from '../../composables/useUiLanguage'
const { t } = useUiLanguage(); const data = ref<CodexActivitySummary | null>(null); const runtime = ref<RuntimeDiagnosticsSnapshot | null>(null); const error = ref(''); const loading = ref(false); const copied = ref(false)
const compact = (value: number) => new Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 1 }).format(value)
const summaryItems = computed(() => data.value ? [{ label: t('Total chats'), value: data.value.totalChats.toLocaleString() }, { label: t('Active days'), value: data.value.activeDays.toLocaleString() }, { label: t('Tokens used'), value: compact(data.value.totalTokens) }, { label: t('Archived'), value: data.value.archivedChats.toLocaleString() }, { label: t('Most used model'), value: data.value.topModel || '—' }, { label: t('Most used reasoning'), value: data.value.topReasoningEffort || '—' }] : [])
const formatTime = (value: string) => new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
async function load() { loading.value = true; error.value = ''; try { const [activity, diagnostics] = await Promise.all([getCodexActivitySummary(), getRuntimeDiagnostics()]); data.value = activity; runtime.value = diagnostics } catch (cause) { error.value = cause instanceof Error ? cause.message : String(cause) } finally { loading.value = false } }
async function copySummary() { if (!runtime.value) return; await navigator.clipboard.writeText(JSON.stringify(runtime.value, null, 2)); copied.value = true; window.setTimeout(() => { copied.value = false }, 1500) }
onMounted(load)
</script>
<style scoped>@reference "tailwindcss";.activity-page{@apply mx-auto w-full max-w-4xl}.activity-page header{@apply mb-7 flex items-start justify-between gap-4}.activity-page h2{@apply text-2xl font-semibold}.activity-page header p,.runtime-heading p{@apply mt-1 text-sm text-zinc-500}.activity-actions{@apply flex gap-2}.activity-actions button{@apply rounded-lg border border-zinc-200 px-3 py-2 text-sm hover:bg-zinc-100 disabled:opacity-50}.activity-summary{@apply grid grid-cols-2 border-y border-zinc-200}.activity-metric{@apply flex items-baseline justify-between gap-4 border-b border-zinc-200 px-1 py-5 odd:mr-6 even:ml-6}.activity-metric:nth-last-child(-n+2){@apply border-b-0}.activity-metric span{@apply text-sm text-zinc-500}.activity-metric strong{@apply max-w-[60%] truncate text-xl font-semibold}.runtime-panel{@apply mt-10 border-y border-zinc-200 py-6}.runtime-heading{@apply flex items-start justify-between}.runtime-heading h3{@apply text-base font-semibold}.runtime-state{@apply rounded-md bg-zinc-100 px-2 py-1 text-xs font-medium uppercase}.runtime-state[data-state=ready]{@apply bg-emerald-100 text-emerald-800}.runtime-state[data-state=starting]{@apply bg-amber-100 text-amber-800}.runtime-counters{@apply mt-5 grid grid-cols-4 gap-3 text-sm text-zinc-500}.runtime-counters span{@apply flex flex-col gap-1}.runtime-counters b{@apply text-lg text-zinc-900}.runtime-error{@apply mt-4 text-sm text-red-700}.runtime-note{@apply mt-4 text-sm text-zinc-500}.runtime-events{@apply mt-5 max-h-64 overflow-y-auto border-t border-zinc-100 pt-2}.runtime-event{@apply flex gap-3 py-1.5 text-xs}.runtime-event time{@apply w-20 shrink-0 text-zinc-400}.runtime-event span{@apply truncate text-zinc-600}.activity-error{@apply mt-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-red-800}.activity-error p{@apply mt-1 text-sm}.activity-loading{@apply border-y border-zinc-200 py-8 text-sm text-zinc-500}@media(max-width:640px){.activity-page header{flex-direction:column}.activity-actions{width:100%}.activity-actions button{flex:1}.activity-summary{grid-template-columns:1fr}.activity-metric{margin:0!important}.activity-metric strong{font-size:1.125rem}.runtime-counters{grid-template-columns:repeat(2,minmax(0,1fr))}}:global(:root.dark) .activity-actions button{border-color:#3f3f46;background:#18181b;color:#f4f4f5}:global(:root.dark) .runtime-counters b{color:#f4f4f5}:global(:root.dark) .runtime-event span{color:#d4d4d8}</style>